---
title: "p8105_hw3_sl4836"
author: "Hun"
date: "10/16/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



#Problem 0
```{r}
getwd()

dir.create(file.path(getwd(), "hw3_data_file"), recursive = TRUE)

list.files()
```


#Problem 1
```{r}
library(p8105.datasets)
data("instacart")
```

```{r}
instacart <- instacart

instacart %>% dim()
instacart %>% names() 
instacart %>% head()

Arranged_aisles <- instacart %>% 
  group_by(aisle) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n))

Arranged_aisles %>% 
  filter(n>10000) %>%
  ggplot(aes(x = reorder(aisle, n), y = n)) + 
  geom_point() + 
  coord_flip()


```



1. There are 134 aisles. Fresh vegetables aisles are the most items ordered from.



```{r}
options(knitr.kable.NA = 0)

baking_top3 <- instacart %>% 
  filter(aisle == "baking ingredients") %>% 
  group_by(product_name) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  slice(1:3) %>%
  mutate(aisle = "baking ingredients")

dog_food_top3 <- instacart %>% 
  filter(aisle == "dog food care") %>% 
  group_by(product_name) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  slice(1:3) %>%
  mutate(aisle = "dog food care")

packaged_vege_fruit_top3 <- instacart %>% 
  filter(aisle == "packaged vegetables fruits") %>% 
  group_by(product_name) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  slice(1:3) %>%
  mutate(aisle = "packaged vegetables fruits")

bind_rows(baking_top3 ,dog_food_top3, packaged_vege_fruit_top3) %>%
  pivot_wider(names_from = product_name, values_from = n)  %>%
  knitr::kable(align = "c", format = "pipe")
```

```{r}
instacart %>% 
  filter(product_name == "Pink Lady Apples" |product_name == "Coffee Ice Cream") %>%
  group_by(product_name, order_dow) %>% 
  summarise(mean_hour = mean(order_hour_of_day)) %>%
  pivot_wider(names_from = order_dow, values_from = mean_hour) %>%
  knitr::kable(align = "c", format = "pipe")
  
```

#Problem 2
```{r}
devtools::install_github("p8105/p8105.datasets")
library(p8105.datasets)

data("brfss_smart2010")
```

```{r}
brfss <- brfss_smart2010


brfss_clean <- brfss %>% 
  janitor::clean_names() %>% 
  filter(topic == "Overall Health") %>%
  filter(response == "Excellent" | response == "Very good" | 
           response == "Good" | response == "Fair" | response == "Poor") %>%
  mutate(response = as.factor(response)) %>% 
  mutate(response = response %>% fct_relevel("Poor", "Fair", "Good", "Very good", "Excellent"))

```

```{r}
brfss_clean %>% 
  filter(year == 2002) %>% 
  group_by(locationabbr) %>% 
  summarise(n = n()) %>% 
  filter(n>6)

brfss_clean %>% 
  filter(year == 2010) %>% 
  group_by(locationabbr) %>% 
  summarise(n = n()) %>% 
  filter(n>6)
```
```{r}
brfss_clean %>% 
  filter(response == "Excellent") %>% 
  select(year, locationabbr, data_value) %>% 
  group_by(year, locationabbr) %>%
  summarise(mean_data_value = mean(data_value)) %>%
  ggplot(aes(year, mean_data_value, color=locationabbr)) + 
  geom_point(size=0.2) + 
  geom_line(aes(group=locationabbr, alpha = 0.2))
```
```{r}
library(ggridges)

brfss_clean %>% filter(year == 2006 | year == 2010 ) %>% filter(locationabbr == "NY") %>% 
  ggplot(aes(data_value,response)) +
  geom_density_ridges(scale=.85) +
  facet_wrap(.~year)
```
#Problem 3
```{r}
accel <- read.csv("~/Downloads/accel_data.csv") 

clean_accel <- accel %>% 
  janitor::clean_names() %>% 
  pivot_longer(activity_1:activity_1440, 
               names_to = "minutes_in_a_day", values_to = "activity_count") %>%
  mutate(day = day %>% 
           fct_relevel("Monday", "Tuesday", "Wednesday", 
                       "Thursday","Friday", "Saturday", "Sunday")) %>% 
  mutate(weekday_vs_weekend = ifelse(day %in% c("Monday", "Tuesday", "Wednesday", 
                       "Thursday","Friday"), "weekday","weekend")) %>% view()
  
  #pivot_wider(names_from = day, values_from = "activity_count") %>% 
  #relocate(Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) %>% view

clean_accel %>% 
  group_by(day) %>% 
  summarize(total = sum(activity_count)) %>% 
  knitr::kable(align = "c", format = "pipe")

```

```{r}
clean_accel %>%
  group_by(day, minutes_in_a_day) %>%
  ggplot(aes(activity_type, activity_count, color = day)) +
  geom_point() 

```

```{r}

```







